<?php

return [
    'label' => 'WIS-CMS',

    /*
    | Feature flags and default behaviors for this profile. Capabilities
    | drive the UI and soft defaults ONLY — authorization stays with Spatie
    | permissions. Modules are self-contained feature packages that stay
    | inert (no tables/routes/UI) while disabled.
    */
    'capabilities' => [
        'attendance' => [
            // 'register'  = per-member/per-child attendance_records
            // 'headcount' = church-wide Men / Women / Children tally
            'default_mode' => 'register',
        ],
        // Whether the Cells module is part of this install's workflow.
        // Sidebar + router hide /cells/* when false.
        'cells' => [
            'enabled' => true,
        ],
        'modules' => [
            'confirmations' => false,
        ],
    ],

    /*
    | Profile-specific labels and asset paths. Core code must never contain
    | WIS-specific wording — anything like that belongs here.
    */
    'strings' => [
        'app.title' => 'WIS-CMS',
        'app_name' => 'Wesleyan International Society',
        'tagline' => 'With God all things are possible',
        'logo' => '/images/wis-logo.png',
        'logo_webp' => '/images/wis-logo.webp',
        'favicon' => '/favicon.png',
        'reports.footer' => 'Generated by WIS-CMS',
    ],

    /*
    | Reference data seeded by the profile-driven seeders. Values below
    | mirror the previous hardcoded arrays verbatim so the default profile
    | seeds identically to before.
    */
    'reference_data' => [
        // Flat union of every permission granted to any role. super_admin
        // receives ALL permissions (the '*' sentinel in 'roles' below).
        'permissions' => [
            'view members', 'create members', 'edit members', 'delete members', 'export members',
            'view children', 'create children', 'edit children', 'delete children',
            'view visitors', 'create visitors', 'edit visitors', 'delete visitors',
            'view attendance', 'create attendance', 'edit attendance', 'delete attendance',
            'view departments', 'create departments', 'edit departments', 'delete departments',
            'view cells', 'create cells', 'edit cells', 'delete cells',
            'manage cell members', 'message own cell',
            'manage department members',
            'view finance', 'create transactions', 'edit transactions', 'delete transactions', 'export finance',
            'view messages', 'send messages', 'message own department',
            'view reports', 'export reports',
            'manage users', 'manage roles', 'manage branches', 'manage service types',
            'manage finance categories', 'view audit log',
            'access portal',
            'view birthday messages', 'manage birthday messages',
            'view service reminders', 'manage service reminders',
            'view member submissions', 'manage member submissions',
            'view pastoral notes', 'create pastoral notes', 'update pastoral notes', 'delete pastoral notes',
        ],

        // role name => ['permissions' => [...]]. '*' grants every permission.
        'roles' => [
            'super_admin' => ['permissions' => '*'],
            'pastor' => ['permissions' => [
                'view members', 'view children', 'view visitors', 'view attendance',
                'view departments', 'view cells', 'view finance', 'view messages', 'view reports',
                'export reports', 'export members', 'export finance',
                'view birthday messages', 'manage birthday messages',
                'view service reminders', 'manage service reminders',
                'view member submissions', 'manage member submissions',
                'view pastoral notes', 'create pastoral notes', 'update pastoral notes', 'delete pastoral notes',
            ]],
            'secretary' => ['permissions' => [
                'view members', 'create members', 'edit members', 'export members',
                'view children', 'create children', 'edit children',
                'view visitors', 'create visitors', 'edit visitors',
                'view attendance', 'create attendance', 'edit attendance',
                'view departments', 'create departments', 'edit departments',
                'manage department members',
                'view cells', 'create cells', 'edit cells', 'delete cells',
                'manage cell members',
                'view messages', 'send messages',
                'view reports', 'export reports',
                'view birthday messages',
                'view service reminders',
                'view member submissions', 'manage member submissions',
                'view pastoral notes', 'create pastoral notes', 'update pastoral notes',
            ]],
            'finance_officer' => ['permissions' => [
                'view finance', 'create transactions', 'edit transactions',
                'delete transactions', 'export finance',
                'view members', 'view reports', 'export reports',
            ]],
            'department_leader' => ['permissions' => [
                'view members', 'view departments', 'manage department members',
                'view attendance', 'create attendance', 'view reports',
                'message own department',
            ]],
            'cell_leader' => ['permissions' => [
                'view members', 'create members', 'edit members', 'view cells', 'manage cell members',
                'view attendance', 'create attendance', 'view reports',
                'message own cell',
                'view birthday messages',
                'view service reminders',
                'view pastoral notes', 'create pastoral notes', 'update pastoral notes',
            ]],
            'children_ministry_leader' => ['permissions' => [
                'view members', 'create members', 'edit members', 'view cells', 'manage cell members',
                'view attendance', 'create attendance', 'view reports',
                'message own cell',
                'view birthday messages',
                'view service reminders',
                'view children', 'create children', 'edit children',
            ]],
            'usher' => ['permissions' => [
                'view members', 'view children', 'create attendance', 'view attendance',
            ]],
            'member' => ['permissions' => [
                'access portal',
            ]],
        ],

        // Mirrors ServiceTypeSeeder exactly.
        'service_types' => [
            ['name' => 'Sunday Adult Service',    'slug' => 'sunday_adult',       'type' => 'adult',    'description' => 'Main Sunday worship service for adults'],
            ['name' => 'Sunday Children Service', 'slug' => 'sunday_children',    'type' => 'children', 'description' => 'Sunday service for children'],
            ['name' => 'Bible Study',             'slug' => 'bible_study',        'type' => 'combined', 'description' => 'Bible study session'],
            ['name' => 'Midweek Service',         'slug' => 'midweek_service',    'type' => 'combined', 'description' => 'Wednesday evening midweek worship service'],
            ['name' => 'Prayer Meeting',          'slug' => 'prayer_meeting',     'type' => 'combined', 'description' => 'Weekly prayer and intercession meeting'],
            ['name' => 'Special Service',         'slug' => 'special_service',    'type' => 'combined', 'description' => 'Special events and services'],
            ['name' => 'Cell Meeting',            'slug' => 'cell_meeting',       'type' => 'combined', 'description' => 'Weekly cell group fellowship meeting'],
            ['name' => 'Department Meeting',      'slug' => 'department_meeting', 'type' => 'combined', 'description' => 'Department-level meeting (Choir, Ushers, etc.)'],
        ],

        // Mirrors FinanceCategorySeeder exactly. 'order' is only meaningful
        // for expenses (display_order); income rows use list position.
        'finance_categories' => [
            'income' => [
                ['name' => 'Tithe',                            'description' => 'Individual tithe contributions'],
                ['name' => 'Offertory',                        'description' => 'General Sunday offertory collection'],
                ['name' => 'Sunday School Offertory',          'description' => 'Sunday school class offerings'],
                ['name' => 'Methodist Development Fund (MDF)', 'description' => 'Connexional development levy'],
                ['name' => 'Welfare',                          'description' => 'Welfare fund contributions from members'],
                ['name' => 'Thanksgiving',                     'description' => 'Thanksgiving offerings'],
                ['name' => 'Day Born Offering',                'description' => 'Day-born / birthday offerings'],
                ['name' => 'Scholarship Fund',                 'description' => 'Scholarship and education support contributions'],
                ['name' => 'Pledges Redemption',               'description' => 'Redemption of pledges made'],
                ['name' => 'Harvest',                          'description' => 'Harvest thanksgiving offerings'],
                ['name' => 'Children Harvest',                 'description' => 'Harvest thanksgiving offerings children'],
                ['name' => 'Mens Harvest',                     'description' => 'Harvest thanksgiving offerings mens'],
                ['name' => 'Womens Harvest',                   'description' => 'Harvest thanksgiving offerings womens'],
                ['name' => 'Others',                           'description' => 'Other miscellaneous income'],
            ],
            'expense' => [
                ['name' => 'Allowance',     'description' => 'Allowances paid to clergy and staff',          'order' => 1],
                ['name' => 'Communication', 'description' => 'Phone, SMS, and internet costs',               'order' => 10],
                ['name' => 'Events',        'description' => 'Event planning and execution costs',           'order' => 11],
                ['name' => 'Maintenance',   'description' => 'Building and equipment maintenance',           'order' => 12],
                ['name' => 'Other Expense', 'description' => 'Miscellaneous expenses',                       'order' => 13],
                ['name' => 'Outreach',      'description' => 'Evangelism and outreach activities',           'order' => 14],
                ['name' => 'Salaries',      'description' => 'Staff and worker remuneration',                'order' => 15],
                ['name' => 'Stationery',    'description' => 'Office and administrative supplies',           'order' => 16],
                ['name' => 'Transport',     'description' => 'Travel and transport costs',                   'order' => 17],
                ['name' => 'Utilities',     'description' => 'Electricity, water, and other utilities',      'order' => 18],
                ['name' => 'Welfare',       'description' => 'Member welfare and support payments',          'order' => 19],
            ],
        ],

        // Mirrors CellSeeder exactly. leader_user_email maps to the User
        // record whose email matches (used to assign cell leaders).
        'cells' => [
            ['name' => 'Peace',             'description' => 'Cell group'],
            ['name' => 'Faithfulness',      'description' => 'Cell group'],
            ['name' => 'Patience 1',        'description' => 'Cell group'],
            ['name' => 'Patience 2',        'description' => 'Cell group', 'leader_user_email' => '%evander%'],
            ['name' => 'Joy',               'description' => 'Cell group'],
            ['name' => 'Love',              'description' => 'Cell group'],
            ['name' => 'Children Ministry', 'description' => 'Children service attendance'],
        ],

        // Branch defaults (overridable per install via CHURCH_NAME /
        // CHURCH_LOCATION env vars).
        'branch' => [
            'name' => 'Wesleyan International Society',
            'location' => 'Kumasi, Ghana',
        ],
    ],
];
