<?php

namespace Tests\Feature;

use App\Diocese\Diocese;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Tests\TestCase;

class DioceseProfileTest extends TestCase
{
    private function controller(): Controller
    {
        return new class extends Controller
        {
            public function logo(): ?string
            {
                return $this->pdfLogoPath();
            }
        };
    }

    public function test_pdf_logo_path_resolves_the_profiles_logo_file(): void
    {
        $png = base64_decode(
            'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
            true
        );
        $name = 'wis-logo-test-'.uniqid().'.png';
        $file = public_path('images/'.$name);
        File::put($file, $png);

        try {
            config(['diocese.strings.logo' => '/images/'.$name]);

            $uri = $this->controller()->logo();

            $this->assertIsString($uri);
            $this->assertStringStartsWith('data:', $uri);
            $this->assertStringContainsString(';base64,', $uri);
            $this->assertSame(base64_encode($png), explode(';base64,', $uri)[1]);
        } finally {
            File::delete($file);
        }
    }

    public function test_pdf_logo_path_returns_null_when_the_logo_file_is_missing(): void
    {
        config(['diocese.strings.logo' => '/definitely/not/a/real/file.png']);

        $this->assertNull($this->controller()->logo());
    }

    public function test_pdf_logo_path_returns_null_when_no_logo_is_configured(): void
    {
        config(['diocese.strings.logo' => null]);

        $this->assertNull($this->controller()->logo());
    }

    public function test_pdf_logo_path_passes_embedded_assets_through_unmodified(): void
    {
        config(['diocese.strings.logo' => 'data:image/png;base64,aW1hZ2U=']);

        $this->assertSame('data:image/png;base64,aW1hZ2U=', $this->controller()->logo());
    }

    public function test_dotted_profile_strings_resolve_even_though_the_keys_are_stored_literally(): void
    {
        // Mirror how the profile files store strings: dotted keys are
        // literal array keys (config()->set would nest them and mask the bug).
        config()->set('diocese.strings', [
            'app.title' => 'MCC-CMS',
            'reports.footer' => 'Generated by MCC-CMS',
            'logo' => '/images/mcgh-logo.png',
        ]);

        $this->assertSame('MCC-CMS', Diocese::string('app.title'));
        $this->assertSame('Generated by MCC-CMS', Diocese::string('reports.footer'));
        $this->assertSame('/images/mcgh-logo.png', Diocese::string('logo'));
        $this->assertNull(Diocese::string('missing.key'));
        $this->assertSame('fallback', Diocese::string('missing.key', 'fallback'));
    }

    public function test_app_meta_partial_renders_the_profiles_branding(): void
    {
        config()->set('diocese.strings', [
            'app.title' => 'MCC-CMS',
            'app_name' => 'Methodist Church Ghana',
            'tagline' => 'With God all things are possible',
            'logo' => '/images/mcgh-logo.png',
            'favicon' => '/favicon-mcgh.png',
        ]);

        $html = view('partials.app-meta', [
            'appTitle' => Diocese::string('app.title'),
            'appName' => Diocese::string('app_name'),
            'tagline' => Diocese::string('tagline'),
            'logo' => Diocese::string('logo'),
            'favicon' => Diocese::string('favicon'),
        ])->render();

        $this->assertStringContainsString('window.APP_META', $html);
        $this->assertStringContainsString('"appTitle":"MCC-CMS"', $html);
        $this->assertStringContainsString('"appName":"Methodist Church Ghana"', $html);
        $this->assertStringContainsString('"logo":"/images/mcgh-logo.png"', $html);
        $this->assertStringContainsString('"favicon":"/favicon-mcgh.png"', $html);
    }

    public function test_welcome_shell_injects_profile_branding_and_favicon(): void
    {
        $manifest = public_path('build/manifest.json');
        if (! file_exists($manifest)) {
            $this->markTestSkipped('Vite build manifest not present — run `npm run build` first.');
        }

        config()->set('diocese.strings', [
            'app.title' => 'MCC-CMS',
            'app_name' => 'Methodist Church Ghana',
            'logo' => '/images/mcgh-logo.png',
            'favicon' => '/favicon-mcgh.png',
        ]);

        $html = view('welcome')->render();

        $this->assertStringContainsString('MCC-CMS — Methodist Church Ghana', $html);
        $this->assertStringContainsString('href="'.asset('/favicon-mcgh.png'), $html);
        $this->assertStringContainsString('"appTitle":"MCC-CMS"', $html);
        $this->assertStringContainsString('"logo":"/images/mcgh-logo.png"', $html);
    }
}
